config/routes.rb
Rails.application.routes.draw do
  ###Devise
  #Users::~~DeviseController
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }


  # #Administrators::~~DeviseController
  devise_for :administrators, controllers: {
    sessions:      'administrators/sessions',
    registrations: 'administrators/registrations'
  }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  #ReviewController
  # resources :reviews, only: [:index, :edit, :update, :destroy ,:new ,:create]
  resources :reviews, only: [:index, :edit, :update, :destroy, :new, :create]
  #delete '/reviews/:review_id',to: 'reviews#destroy', as: 'hogeo'


  #get 'users/show'
  #get 'users/edit', to: 'users#edit'
  get 'users/:id/remove/', to: 'users#remove', as: 'user_remove'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ###ルートURL
  root 'items#index'
  ###エンドユーザー###
  #UsersController
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'warn'
      patch 'unsubscribe'
    end
   end

  #ItemsController
  resources :items, only: :show
  get '/items/category/:category_id', to: 'items#category', as: :category

  #FavoritesController
  resources :favorites, only: [:index, :create, :destroy]


  ###管理者###
  #Admin::UsersController
  get '/admin', to: 'admin/users#top' #管理者側のルートURL

  #Admin::End_UsersController
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update]
    patch '/end_users/remove/:id', to: 'end_users#remove', as: :remove ##設計と違う箇所
  end

  #Admin::ItemsController
  namespace :admin do
    resources :items, only: [:index, :show, :edit, :update, :new, :create]
    put 'items/stop/:id', to: 'items#stop', as: :stop
    get'items/category/:category_id',to: 'items#category', as: :category
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, through: :favorites
  has_many :favorites

  # validates :user_name, presence: true, length: { maximum: 50, minimum: 1 }
  validates :email, presence: true
  validates :encrypted_password, presence: true
  # validates :is_delete, presence: true

   enum is_delete: {  exist: 0, remove: 1 }

  attachment :profile_image

  #favorites関連

  #いいねする
  def iine(item)
    favorite = favorites.build(item_id: item.id)
    favorite.save
  end

  #いいねを外す
  def uniine(item)
    favorite = favorites.find_by(item_id: item.id)
    favorite.destroy
  end

  #現在のユーザーがそのカクテルに対していいねしているか
  def iine?(item)
    favorites.exists?(item_id: item.id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_administrator!

def top

end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

    protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :user_name, :email, :is_delete
    ])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    # before_action :logical_delete_user
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    def new
       super
    end
end

app/controllers/users/users_registrations_controller.rb
class UsersRegistrationsController < ApplicationController
    protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :first_name, :last_name, :kana_first, :kana_last, :postal_code,
      :address, :phone_number
    ])
  end
end

app/controllers/users/users_sessions_controller.rb
class UsersSessionsController < ApplicationController
    before_action :logical_delete_user, only: :create
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    def new
       super
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logical_delete_user, only: [:show, :edit, :update, :unsubscribe]
    before_action :authenticate_user!

    def show
        @user = User.find(params[:id])
       unless @user.id == current_user.id
       redirect_to user_path(@current_user)
   end
    end

    def edit
        @user = User.find(params[:id])
       unless @user.id == current_user.id
       redirect_to user_path(@current_user)
      end
    end
  def remove
    @user = User.find(current_user.id)
  end

        def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "You have update user successfully."
        redirect_to user_url(@user)
      else
        render :edit
      end
    end

    def unsubscribe
      user = current_user
      user.is_delete = 1
      user.save
      redirect_to logout_path
    end

  private
  def user_params
      params.require(:user).permit(:user_name, :email, :profile_image ,:encrypted_password, :birth_date, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="form-wrapper">
  <h1>マイページ編集</h1>
<%= form_for(@user) do |f| %>
 <h4>プロフィール画像</h4>
 <div class="form-group has-icon">
    <div class="user-edit-image">
        <%= attachment_image_tag @user, :profile_image,size: "250x300", class: "img-circle pull-left profile-thumb", fallback: "no_image.png"%>
    </div>
    <label class="control-label sr-only" for="user_profile_image">ProfileImage</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
</div>

  <div class="form-item">
    <h4>ニックネーム<%= f.text_field :user_name %></h4>
  <h4>メールアドレス  <%= f.text_field :email %></h4>
  </div>

    <div class="form-item">
  <%= f.label :生年月日 %>
  <%= raw sprintf(
      f.date_select(
        :birth_date,
        use_month_numbers: true,
        start_year: 1930,
        end_year: (Time.now.year - 18),
        default: Date.new(1989, 1, 1),
        date_separator: '%s'),
        '年 ', '月 ') + '日' %>

</div>

  <div class="field">
    <%= f.label :パスワード %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password", class:"form-detail" %>
  </div>

  <div class="field">
    <%= f.label :確認用パスワード %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"form-detail" %>
  </div><br>

  <div class="form-item">
    <%= f.label :introduction, "自己紹介文" %>
    <%= f.text_area :introduction, class:"自己紹介", row:10 %>
  </div>

  <div class="button-panel">
  <%= f.submit '更新する', class: "button" %>
  </div>

<% end %>

app/views/users/remove.html.erb
<div class="notice">
	<h1>退会しますか？</h1>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div class="remove">
				<%= link_to "退会する", unsubscribe_users_path(@user), method: :patch, class:'btn btn-danger' %>
			</div>
		</div>

        <div class="col-md-6">
			<div class="stop">
				<%= link_to "やっぱりやめる", user_path(current_user.id), class:'btn btn-primary' %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="wrap">
  <div class="notice">
    <h1>マイページ</h1>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-xs-4">
          <h3 class="prof-n-kan">ニックネーム</h3>
          <%= @user.user_name %>
      </div>
    </div>

    <div class="row">
        <div class="col-xs-4">
          <%= attachment_image_tag @user, :profile_image, class: "img-circle profile-thumb", fallback: "no_image.png", size:'250x300'%>
        </div>

        <div class="col-xs-8">
            <h3 class="prof-introduction">自己紹介</h3>
            <%= @user.introduction %>
        </div><br>
    </div>

    <div class="row">
      <div class="col-xs-4">
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="19.427" height="18.821" viewBox="0 0 19.427 18.821">
              <g id="アートワーク_14" data-name="アートワーク 14" transform="translate(9.713 9.411)">
              <g id="グループ_30" data-name="グループ 30" transform="translate(-9.713 -9.411)">
              <path id="パス_76" data-name="パス 76" d="M0,1.783V12.959a1.783,1.783,0,0,0,1.783,1.783H7.628l6.639,4.041a.274.274,0,0,0,.383-.359L12.74,14.739h4.9a1.783,1.783,0,0,0,1.783-1.783V1.783A1.783,1.783,0,0,0,17.644,0H1.783A1.783,1.783,0,0,0,0,1.783Zm1.362,0a.424.424,0,0,1,.421-.421H17.644a.424.424,0,0,1,.417.417v11.18a.424.424,0,0,1-.417.417H10.5l1.146,2.214L8.007,13.377H1.783a.424.424,0,0,1-.417-.417Z"/>
              <g id="グループ_29" data-name="グループ 29" transform="translate(3.824 3.159)">
              <path id="パス_77" data-name="パス 77" d="M112.587,93.973a.837.837,0,0,1,0-1.673h9.01a.837.837,0,0,1,0,1.673Z" transform="translate(-111.75 -92.3)"/>
              <path id="パス_78" data-name="パス 78" d="M112.587,192.673a.837.837,0,1,1,0-1.673h10.1a.837.837,0,1,1,0,1.673Z" transform="translate(-111.75 -187.622)"/>
              <path id="パス_79" data-name="パス 79" d="M112.587,291.173a.837.837,0,1,1,0-1.673h6.943a.837.837,0,1,1,0,1.673Z" transform="translate(-111.75 -282.752)"/>
                </g>
              </g>
            </g>
            </svg><%= link_to "コメント履歴", reviews_path ,:style => "color:black;"%></h3><br>

          <h3>
              <svg xmlns="http://www.w3.org/2000/svg" width="19.427" height="18.821" viewBox="0 0 19.427 18.821">
              <g id="アートワーク_14" data-name="アートワーク 14" transform="translate(9.713 9.411)">
              <g id="グループ_30" data-name="グループ 30" transform="translate(-9.713 -9.411)">
              <path id="パス_76" data-name="パス 76" d="M0,1.783V12.959a1.783,1.783,0,0,0,1.783,1.783H7.628l6.639,4.041a.274.274,0,0,0,.383-.359L12.74,14.739h4.9a1.783,1.783,0,0,0,1.783-1.783V1.783A1.783,1.783,0,0,0,17.644,0H1.783A1.783,1.783,0,0,0,0,1.783Zm1.362,0a.424.424,0,0,1,.421-.421H17.644a.424.424,0,0,1,.417.417v11.18a.424.424,0,0,1-.417.417H10.5l1.146,2.214L8.007,13.377H1.783a.424.424,0,0,1-.417-.417Z"/>
              <g id="グループ_29" data-name="グループ 29" transform="translate(3.824 3.159)">
              <path id="パス_77" data-name="パス 77" d="M112.587,93.973a.837.837,0,0,1,0-1.673h9.01a.837.837,0,0,1,0,1.673Z" transform="translate(-111.75 -92.3)"/>
              <path id="パス_78" data-name="パス 78" d="M112.587,192.673a.837.837,0,1,1,0-1.673h10.1a.837.837,0,1,1,0,1.673Z" transform="translate(-111.75 -187.622)"/>
              <path id="パス_79" data-name="パス 79" d="M112.587,291.173a.837.837,0,1,1,0-1.673h6.943a.837.837,0,1,1,0,1.673Z" transform="translate(-111.75 -282.752)"/>
                </g>
              </g>
            </g>
            </svg>
          <%= link_to "お気に入りレシピ", favorites_path ,:style => "color:black;"%></h3>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <div class="edit">
          <%= link_to "マイページ編集", edit_user_path , class:'btn btn-success', :style=>"color:black;"%>
        </div>

        <div class="remove">
          <%= link_to "退会する",  user_remove_path , class:'btn btn-danger', :style=>"color:black;"%>
        </div>
      </div>
    </div>
  </div>
</div>