config/routes.rb
Rails.application.routes.draw do
  ###Devise
  #Users::~~DeviseController
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }


  # #Administrators::~~DeviseController
  devise_for :administrators, controllers: {
    sessions:      'administrators/sessions',
    registrations: 'administrators/registrations'
  }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  #ReviewController
  # resources :reviews, only: [:index, :edit, :update, :destroy ,:new ,:create]
  resources :reviews, only: [:index, :edit, :update, :destroy, :new, :create]
  #delete '/reviews/:review_id',to: 'reviews#destroy', as: 'hogeo'


  #get 'users/show'
  #get 'users/edit', to: 'users#edit'
  get 'users/:id/remove/', to: 'users#remove', as: 'user_remove'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ###ルートURL
  root 'items#index'
  ###エンドユーザー###
  #UsersController
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'warn'
      patch 'unsubscribe'
    end
   end

  #ItemsController
  resources :items, only: :show
  get '/items/category/:category_id', to: 'items#category', as: :category

  #FavoritesController
  resources :favorites, only: [:index, :create, :destroy]


  ###管理者###
  #Admin::UsersController
  get '/admin', to: 'admin/users#top' #管理者側のルートURL

  #Admin::End_UsersController
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update]
    patch '/end_users/remove/:id', to: 'end_users#remove', as: :remove ##設計と違う箇所
  end

  #Admin::ItemsController
  namespace :admin do
    resources :items, only: [:index, :show, :edit, :update, :new, :create]
    put 'items/stop/:id', to: 'items#stop', as: :stop
    get'items/category/:category_id',to: 'items#category', as: :category
  end
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :materials, inverse_of: :item, dependent: :destroy
    has_many :howtomakes, inverse_of: :item, dependent: :destroy
    accepts_nested_attributes_for :materials, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :howtomakes, reject_if: :all_blank, allow_destroy: true

    has_many :users, through: :favorites, through: :reviews
    has_many :favorites
    has_many :reviews
    belongs_to :category



    validates :cocktail_name, presence: true, length: { maximum: 200, minimum: 1 }
    validates :category_id, presence: true

    enum listing_stop: { default: 0, stop: 1 }

    attachment :cocktail_image
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_administrator!

    PER = 9

    def index
        # @items = Item.where(listing_stop: 0).page(params[:page]).per(PER)
        # @items = Item.all
        @item_ranks = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(5).pluck(:item_id))

    end

    def category
        @category_items = Item.where(category_id: params[:category_id])
        @category = Item.where(category_id: params[:category_id]).where(listing_stop: 0).page(params[:page]).per(PER)
    end

    def show
        @item = Item.find(params[:id])
        @categories = Category.all
        # render 'items/show'
    end

    def new
        @item = Item.new
        @material = @item.materials.build
        @howtomake = @item.howtomakes.build
        @categories = Category.all
    end

    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to admin_item_url(@item)
        else
            render 'new'
        end

    end

    def edit
        @item = Item.find(params[:id])
    end

    def update
        @item = Item.find(params[:id])
        if @item.update_attributes(item_params)
            redirect_to admin_item_url
        else
            render 'edit'
        end
    end

    def stop
        @item = Item.find(params[:id])
        @item.update_attributes(listing_stop: 1)
        redirect_to admin_items_url
    end


    private

    def item_params
        params.require(:item).permit(
                :category_id, :cocktail_name, :cocktail_taste, :cocktail_color,:cocktail_introduction,
                :alcohol_content, :cocktail_image, :manufacturing_method,
                    materials_attributes: [:id, :material, :_destroy],
                     howtomakes_attributes: [:id, :howtomake, :_destroy]
                )
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :logical_delete_user
  before_action :authenticate_user!
    PER = 5

    def index
        #@items = Item.all.
        @item_ranks = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(5).pluck(:item_id))
    end

    def category
      # @category = params[:category_id]
        @category_items = Item.where(category_id: params[:category_id])
        @category = Item.where(category_id: params[:category_id]).where(listing_stop: 0).page(params[:page]).per(PER)
    end

    def show
        @item = Item.find(params[:id])
        @categories = Category.all
    end

    # def new
    #   @item = Item.new
    #   @material = @item.materials.build
    #   @howtomake = @item.howtomakes.build
    #   @categories = Category.all
    # end

    # def create
    #   @item = Item.new(item_params)
    #   if @item.save!
    #       redirect_to item_url(@item)
    #   else
    #       render 'new'
    #   end

    # end

    # def edit
    #   @item = Item.find(params[:id])
    # end

    # def update
    #   @item = Item.find(params[:id])
    #   if @item.update_attributes(item_params)
    #       redirect_to item_url
    #   else
    #       render 'edit'
    #   end
    # end

    # def stop
    #   @item = Item.find(params[:id])
    #   @item.update_attributes(listing_stop: 1)
    #   redirect_to items_url
    # end

  def check_login
    redirect_to logout_path if current_user && current_user.active_flag != 'active'
  end

  private

  def item_params
      params.require(:item).permit(
              :category_id, :cocktail_name, :cocktail_taste, :cocktail_color,:cocktail_introduction,
              :alcohol_content, :cocktail_image, :manufacturing_method,
                  materials_attributes: [:id, :material, :_destroy],
                   howtomakes_attributes: [:id, :howtomake, :_destroy]
              )
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/category.html.erb
<div class="row background-category <%= @category %>">
    <div class="col-md-2">
    <%= render 'layouts/category', roll: 'users'%>
    </div>

    <div class="col-md-10">
    <h1><%= Category.find(params[:category_id])[:category_name] %>ベース一覧</h1>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="row">
                <% @category.each do |category_item| %>
                        <div class="col-md-4">
                            <%= attachment_image_tag category_item, :cocktail_image, fallback: "no_image.png", size:'200x250'  %> <br>
                            <p class="category-font"><%= category_item.cocktail_name%></p> <p class="category-font2"><%= link_to ">>レシピを見る", item_path(category_item.id) %></p>
                        </div>
                <% end %>
            </div>
        </div>
    </div>
  <%= paginate @category %>
</div>

app/views/items/edit.html.erb
<div class="row">
    <h1>カクテル編集</h1>

    <%= form_for(@item, url: item_path(@item)) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="form-group">
            <%= f.attachment_field :cocktail_image %>
        </div>

		<div class="form-group">
            <%= f.label :cocktail_name, "カクテル名" %>
			<%= f.text_field :cocktail_name, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :artist_id, "テイスト" %>
			<%= f.text_field :cocktail_taste, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :cocktail_color, "カラー" %>
			<%= f.text_field :cocktail_color, class:"form-control" %>
		</div>

		<div class="form-group">
            <%= f.label :manufacturing_method, "製造方法" %>
            <%= f.text_field :manufacturing_method, class:"form-control" %>
        </div>

        <div class="form-group">
			<%= f.label :alcohol_content, "度数" %>
			<%= f.text_field :alcohol_content, class:"form-control" %>
		</div>

        <div class="form-group">
            <%= f.label :cocktail_introduction, "カクテルの説明" %>
            <%= f.text_field :cocktail_introduction, class:"form-control" %>
        </div>

        <div class="form-group">
			<%= f.label :category, "カテゴリー" %>
            <% Category.all.each do |category| %>
            <label><%= f.radio_button :category_id, category.id %> <%= category.category_name %></label>
            <% end %>
		</div>

        <h3>材料</h3>
        <div class="materials">
            <%= f.fields_for :materials do |material| %>
                <%= render 'material_fields', f: material %>
            <% end %>
            <div class="links">
                <%= link_to_add_association '材料を追加', f, :materials, class:"btn btn-primary" %>
            </div>
        </div>

        <h3>作り方</h3>
        <div class="howtomakes">
            <%= f.fields_for :howtomakes do |howtomake| %>
                <%= render 'howtomake_fields', f: howtomake %>
            <% end %>
            <div class="links">
                <%= link_to_add_association '手順を追加', f, :howtomakes, class:"btn btn-primary" %>
            </div>
        </div>

        <div class="item-edit-btn">
        <%= f.submit '編集完了', class:"btn btn-primary" %>
        </div>
	<% end %>
</div>

app/views/items/new.html.erb
<div class="row">
    <h1>カクテル追加</h1>
<% @item.errors.full_messages.each do |mes | %>
<%= mes%>
<% end %>
    <%= form_for(@item, url: items_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="form-group">
            <%= f.attachment_field :cocktail_image %>
        </div>

		<div class="form-group">
			<%= f.label :cocktail_name, "カクテル名" %>
			<%= f.text_field :cocktail_name, class:"form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :cocktail_taste, "テイスト" %>
			<%= f.text_field :cocktail_taste, class:"form-control" %>
		</div>


		<div class="form-group">
            <%= f.label :cocktail_color, "カラー" %>
            <%= f.text_field :cocktail_color, class:"form-control" %>
        </div>

		<div class="form-group">
            <%= f.label :manufacturing_method, "製造方法" %>
            <%= f.text_field :manufacturing_method, class:"form-control" %>
        </div>

		<div class="form-group">
            <%= f.label :alcohol_content, "度数" %>
            <%= f.text_field :alcohol_content, class:"form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :cocktail_introduction, "カクテルの説明" %>
            <%= f.text_field :cocktail_introduction, class:"form-control" %>
        </div>

        <div class="form-group">
			<%= f.label :category, "カテゴリー" %>
            <% Category.all.each do |category| %>
            <label><%= f.radio_button :category_id, category.id %> <%= category.category_name %></label>
            <% end %>
		</div>

        <h3>材料</h3>
        <div class="materials">
            <%= f.fields_for :materials do |material| %>
                <%= render 'material_fields', f: material %>
            <% end %>
            <div class="links">
                <%= link_to_add_association '材料を追加', f, :materials, class:"btn btn-primary" %>
            </div>
        </div>

        <h3>作り方</h3>
        <div class="howtomakes">
            <%= f.fields_for :howtomakes do |howtomake| %>
                <%= render 'howtomake_fields', f: howtomake %>
            <% end %>
            <div class="links">
                <%= link_to_add_association '手順を追加', f, :howtomakes, class:"btn btn-primary" %>
            </div>
        </div>

        <div class="item-add-to">
        <%= f.submit 'カクテルを追加', class:"btn btn-primary" %>
        </div>
	<% end %>
</div>

app/views/items/show.html.erb
<div class="container wrap">
    <div class="row">
        <div class="col-md-6 mt-5">
            <%= attachment_image_tag @item, :cocktail_image, fallback: "no_image.png", size:'450x450'  %>
        </div>

        <div class="col-md-6 mt-5">
            <h3>カクテル名:<%= @item.cocktail_name %></h3><br>
            <h3>度数:<%= @item.alcohol_content %></h3><br>
            <h3>味:<%= @item.cocktail_name %></h3><br>
            <h3>色:<%= @item.cocktail_color %></h3><br>
            <h3>製法:<%= @item.manufacturing_method %></h3><br>
            <div class="col-md-5" id="iine_count">
                <h3><%= @item.favorites.count %> いいね</h3>
            </div>
            <div id="iine-<%= @item.id %>">
                <% if user_signed_in? %>
                <div>
                    <% if current_user && current_user.iine?(@item) %>
                        <%= render 'favorites/unfavorites', item: @item %>
                    <% else %>
                        <%= render 'favorites/favorites', item: @item %>
                    <% end %>
                </div>
            <% end %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            <h3><%= link_to "レビューする", new_review_path << "?item_id=#{@item.id}", class:"btn btn-primary" %></h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-5">
            <h3>材料</h3>
                <table class="table fix-table">
                    <% @item.materials.each do |material| %>
                        <tr>
                            <td class="admin-item-show-td">
                            <td><%= material.material %></td>
                        </tr>
                    <% end %>
                </table>
        </div>

        <div class="col-md-5">
            <h3>作り方</h3>
                <table class="table fix-table">
                    <% @item.howtomakes.each do |howtomake| %>
                        <tr>
                            <td class="admin-item-show-td">
                            <td><%= howtomake.howtomake %></td>
                        </tr>
                    <% end %>
                </table>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <h3>カクテル説明</h3>
                <table class="table fix-table">
                <%= @item.cocktail_introduction %></h4>
                </table>
        </div>
    </div>
</div>