config/routes.rb
Rails.application.routes.draw do
  ###Devise
  #Users::~~DeviseController
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
  }


  # #Administrators::~~DeviseController
  devise_for :administrators, controllers: {
    sessions:      'administrators/sessions',
    registrations: 'administrators/registrations'
  }

  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  #ReviewController
  # resources :reviews, only: [:index, :edit, :update, :destroy ,:new ,:create]
  resources :reviews, only: [:index, :edit, :update, :destroy, :new, :create]
  #delete '/reviews/:review_id',to: 'reviews#destroy', as: 'hogeo'


  #get 'users/show'
  #get 'users/edit', to: 'users#edit'
  get 'users/:id/remove/', to: 'users#remove', as: 'user_remove'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ###ルートURL
  root 'items#index'
  ###エンドユーザー###
  #UsersController
  resources :users, only: [:show, :edit, :update] do
    collection do
      get 'warn'
      patch 'unsubscribe'
    end
   end

  #ItemsController
  resources :items, only: :show
  get '/items/category/:category_id', to: 'items#category', as: :category

  #FavoritesController
  resources :favorites, only: [:index, :create, :destroy]


  ###管理者###
  #Admin::UsersController
  get '/admin', to: 'admin/users#top' #管理者側のルートURL

  #Admin::End_UsersController
  namespace :admin do
    resources :end_users, only: [:index, :show, :edit, :update]
    patch '/end_users/remove/:id', to: 'end_users#remove', as: :remove ##設計と違う箇所
  end

  #Admin::ItemsController
  namespace :admin do
    resources :items, only: [:index, :show, :edit, :update, :new, :create]
    put 'items/stop/:id', to: 'items#stop', as: :stop
    get'items/category/:category_id',to: 'items#category', as: :category
  end
end

app/views/layouts/_admin_header.html.erb
<body>
  <header class="navbar navbar-inverse">
    <div class="container">
      <nav class='nav navbar-nav navbar-left' >
          <h1><%= link_to " Master Boooooze!!! ", admin_path, :style => "color:white;" %></h1>
      </nav>

      <nav>
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to " トップページ ", admin_path ,:style=>"color:white;" %></li>
            <li><%= link_to " ログアウト ", destroy_administrator_session_path, method: :delete ,:style=>"color:white;" %></li>
        </ul>
      </nav>
    </div>
  </header>
</body>

app/views/layouts/_category.html.erb
<div class="category-box">
    <div class="category-logo">
        <span class="logo-text">Cotegory</span>
    </div>
    <div class="category-group">
        <% if roll == 'admin' %>
            <p class="category"><%= link_to "ビールベース", admin_category_path(1), class:"category-link" %></p><br>
            <p class="category"><%= link_to "ワインベース", admin_category_path(2), class:"category-link" %></p><br>
            <p class="category"><%= link_to "焼酎・日本酒ベース", admin_category_path(3), class:"category-link" %></p><br>
            <p class="category"><%= link_to "リキュールベース", admin_category_path(4), class:"category-link" %></p><br>
            <p class="category"><%= link_to "ジンベース", admin_category_path(5), class:"category-link" %></p><br>
            <p class="category"><%= link_to "ウォッカベース", admin_category_path(6), class:"category-link" %></p><br>
            <p class="category"><%= link_to "ラムベース", admin_category_path(7), class:"category-link" %></p><br>
            <p class="category"><%= link_to "テキーラベース", admin_category_path(8), class:"category-link" %></p><br>
        <% else %>
            <p class="category"><%= link_to "ビールベース", category_path(1), class:"category-link" %></p><br>
            <p class="category"><%= link_to "ワインベース", category_path(2), class:"category-link" %></p><br>
            <p class="category"><%= link_to "焼酎・日本酒ベース", category_path(3), class:"category-link" %></p><br>
            <p class="category"><%= link_to "リキュールベース", category_path(4), class:"category-link" %></p><br>
            <p class="category"><%= link_to "ジンベース", category_path(5), class:"category-link" %></p><br>
            <p class="category"><%= link_to "ウォッカベース", category_path(6), class:"category-link" %></p><br>
            <p class="category"><%= link_to "ラムベース", category_path(7), class:"category-link" %></p><br>
            <p class="category"><%= link_to "テキーラベース", category_path(8), class:"category-link" %></p><br>
        <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="mt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <span>© 1991-2019, Boooooze!!!.com, Inc</span>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-8">
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_login_header.html.erb
<header class="navbar navbar-inverse ">
    <div class="container">
        <nav class='nav navbar-nav navbar-left'>
            <ul class="nav navbar-nav" style="width: 200px;">
                <div class="title">
                    <li class="header-li"><%= link_to " Boooooze!!! ", root_path,:style=>"color:white;"%></li>
                </div>
            </ul>
        </nav>
        <nav class='nav navbar-nav navbar-right'>
            <ul class="nav navbar-nav navbar-original">
                <li class="header-li"><%= link_to " マイページ ", user_path(current_user) ,:style => "color:white;"%></li>
                <li class="header-li"><%= link_to " ログアウト ", destroy_user_session_path, method: :delete ,:style => "color:white;"%></li>
                <li class="header-li"><a style="color:green"><%= current_user.user_name %> さんようこそ</a></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_not_login_footer.html.erb
  <footer class="fixed-bottom">
    <div class="container">

        <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <span>© 1991-2019, Boooooze!!!.com, Inc</span>
          </div>
        </div>

        <div class="row">
          <div class="col-md-offset-8">
          </div>
        </div>

    </div>
  </footer>

app/views/layouts/_not_login_header.html.erb
<% unless request.path.include?("administrators") %>

<header class="navbar navbar-inverse navbar-position">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
        <ul class="nav navbar-nav" style="width: 200px;">
        <div class="title">
      <h1><%= link_to " Boooooze!!! ", root_path,:style=>"color:white;"%></h1>
      </div>
    </nav>
    <nav class='nav navbar-nav navbar-right'>
      <ul class="nav navbar-nav navbar-right navbar-original">
          <li class="header-li"><%= link_to " ログイン",new_user_session_path ,:style=>"color:white;"%></li>
          <li class="header-li"><%= link_to " 新規会員登録",new_user_registration_path ,:style=>"color:white;" %></li>
      </ul>
    </nav>
  </div>
</header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="wrapper">
    <% if administrator_signed_in? %>
      <%= render 'layouts/admin_header' %>
    <% elsif user_signed_in? %>
      <%= render 'layouts/login_header' %>
    <% else %>
      <%= render 'layouts/not_login_header' %>
    <% end %>

    <% if false %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="container-fluid p-0">
      <%= yield %>
    </div>
  </div>

    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>